1st que[list into 1D array]


In [1]:
import numpy as np 
list = [1,2,3,4,5]
arr = np.array(list)
print(list)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


2nd que [3X3 matrix in range 2 to 10]


In [5]:

num_range = np.arange(2, 11)
arr1 = num_range.reshape(3, 3)
print(num_range)
print(arr1)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3rd que [null vector with zero's of size 10 ,update 6th value to 11]

In [6]:
vector = np.zeros(10)
print(vector)
vector[6] = 11
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4th que [reverse array]

In [8]:
array = np.arange(12, 38)
print(array)
rev_array = array[::-1]
print(rev_array)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


8th que [list and tuple to array]


In [9]:
list_val = [1,2,3,4,5,6,7,8]
array_list = np.array(list_val)
print(list_val)
print(array_list)
tuple_val = ((8, 4, 6), (1, 2, 3))
array_tuple = np.array(tuple_val)
print(tuple_val)
print(array_tuple)


[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
((8, 4, 6), (1, 2, 3))
[[8 4 6]
 [1 2 3]]


9th que [append the values]

In [10]:
array9 = np.array([10,20,30])
print(array9)
array9 = np.append(array9, [40, 50, 60, 70, 80, 90])
print(array9)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


10 que [real and imaginary part of array]


In [11]:
complex_array = np.array([1+0j, 0.707106+0707106j])
print(complex_array)
real_num = complex_array.real
print(real_num)
imaginary_num = complex_array.imag
print(imaginary_num)

[1.           +0.j 0.707106+707106.j]
[1.       0.707106]
[     0. 707106.]


12 que[comman values]


In [12]:
array12a = np.array([0, 10, 20, 40, 60])
array12b = np.array([10, 30, 40])
print(array12a)
print(array12b)
common_val = np.intersect1d(array12a, array12b)
print(common_val)

[ 0 10 20 40 60]
[10 30 40]
[10 40]


13 que[set difference]

In [13]:
array13a = np.array([0, 10, 20, 40, 60, 80])
array13b = np.array([10, 30, 40, 50, 70, 90])
print(array13a)
print(array13b)
difference = np.setdiff1d(array13a, array13b)
print(difference)


[ 0 10 20 40 60 80]
[10 30 40 50 70 90]
[ 0 20 60 80]


14th que[exclusive -or]

In [14]:
array14a = np.array([0, 10, 20, 40, 60, 80])
array14b = np.array([10, 30, 40, 50, 70])
print(array14a)
print(array14b)
exclusive_or = np.setxor1d(array14a, array14b)
print(exclusive_or)

[ 0 10 20 40 60 80]
[10 30 40 50 70]
[ 0 20 30 50 60 70 80]


15 que[comparing two arrays]

In [15]:
a = np.array([1,2])
b = np.array([4,5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False]
[False False]
[ True  True]
[ True  True]


16 que[flatten array]


In [16]:
array16 =  np.array([[10, 20, 30], [20, 30, 50]])
print(array16)
flatten_array = array16.flatten()
print(flatten_array)

[[10 20 30]
 [20 30 50]]
[10 20 30 20 30 50]


17 que [type casting]

In [17]:
x = np.array([[2, 4, 6], [6, 8, 10]], dtype=np.int32)
print(x)
x = x.astype(np.float64)
print(x)

[[ 2  4  6]
 [ 6  8 10]]
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18 que [ones on diagonal]

In [18]:
array18 = np.eye(3)
print(array18)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20 que [concatenate two arrays]

In [19]:
array20a = np.array([[0, 1, 3],[5, 7, 9]])
array20b = np.array([[0, 2, 4],[6, 8, 10]])
print(array20a)
print(array20b)
concatenated_array = np.concatenate((array20a, array20b), axis=1)
print(concatenated_array)


[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22 que[multiply by 3]

In [20]:
array22 = np.arange(12).reshape(3, 4)
print(array22)
new_array = array22 * 3
print(new_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23 que[numpy array to list]

In [22]:
array23 = np.array([[0, 1], [2, 3],[4, 5]])
print(array23)
list_array = array23.tolist()
print(list_array)

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


27 que [delete specific elements]

In [23]:
array27 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(array27)
del_array = np.delete(array27, [0, 3, 4])
print(del_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  60  70  80  90 100]


24 que[array to list & with precision 3]

In [ ]:
array24 = np.random.rand(10)
print(array24)
precision = np.round(array24, 3)
list_a = precision.tolist()
print(list_a)

[0.14915086 0.08142523 0.22512205 0.0544804  0.20933902 0.18869826
 0.42501577 0.60040566 0.4758156  0.24550263]
[0.149, 0.081, 0.225, 0.054, 0.209, 0.189, 0.425, 0.6, 0.476, 0.246]


5th que [create 2D array with 1 on border and zeros inside]

In [6]:
import numpy as np
array5 = np.ones((5,5))
print(array5)
array5[1:-1,1:-1] = 0
print(array5)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6th que [program to add a border filled with zero's around existing array]

In [10]:
old_array = np.ones((3,3))
print(old_array)
new_arr = np.zeros((5,5))
new_arr[1:-1, 1:-1] = old_array
print(new_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7th que[ checkerboard pattern]

In [14]:
array7 = np.zeros((8,8))
print(array7)
array7[::2,1::2] = 1
array7[1::2, ::2] = 1
print()
print(array7)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


num of elements, elements in bytes,total bytes consumed by elements

In [17]:
array11 = np.array([10,20,30])
print(array11.size)
print(array11.itemsize)
print(array11.nbytes)

3
8
24


15 que [program to save a numpy array to a text file]

In [19]:
array15 = np.array([10,20,30,40,50])
np.savetxt("array_to_text", array15, fmt="%d")


19 que [triangle pattern]

In [30]:
array19 = np.tri(4, 3,k=-1)
print(array19)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21 que [array immutable]

In [31]:
array21 = np.array([25,10,26,11])
array21.flags.writeable = False
array21[0] = 52


ValueError: assignment destination is read-only